//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_StokTakip.Models.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_URUNLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_URUNLER()
        {
            this.TBL_SATISLAR = new HashSet<TBL_SATISLAR>();
        }
    
        public int URUNID { get; set; }

        [Required (ErrorMessage = "Bu Alan Boþ Býrakýlamaz.")]
        public string URUNAD { get; set; }

        [Required (ErrorMessage = "Bu Alan Boþ Býrakýlamaz.")]
        public string MARKA { get; set; }
        public Nullable<short> URUNKATEGORI { get; set; }

        [Required (ErrorMessage = "Bu Alan Boþ Býrakýlamaz.")]
        public Nullable<decimal> FIYAT { get; set; }

        [Required (ErrorMessage = "Bu Alan Boþ Býrakýlamaz.")]
        public Nullable<byte> STOK { get; set; }
    
        public virtual TBL_KATEGORILER TBL_KATEGORILER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SATISLAR> TBL_SATISLAR { get; set; }
    }
}
